### PR TITLE
Add new standup version

### PR DESCRIPTION
**Pull request by MarcelMue**
Tested on AWS and working as intended as far as I can tell.

### CODE REVIEW

**Review by stone-z — APPROVED** [review]
Side thought -- Maybe we should provide a variable for the latest pinned `standup` version for tasks that want to use it

**Comment by MarcelMue** [comment]
> Side thought -- Maybe we should provide a variable for the latest pinned `standup` version for tasks that want to use it

Might be an idea but I don't know if you can use a variable in the image. Like will it be interpreted by something?

I tried to template this image before but turns out it's harder than expected. We use kustomize to render these first and maybe I am just bad at it :D

**Comment by stone-z** [comment]
Not in the image itself, but for kustomize

**Comment by MarcelMue** [comment]
> Not in the image itself, but for kustomize

ACK - when I tried I couldn't make it work in kustomize. Might be that I am missing something obvious.

**Pull request merged**
