### PR TITLE
heartbeat create cluster

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/roadmap/issues/454

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
image

**Comment by MarcelMue** [comment]
Can you give some context here? Why does `create-cluster` not work?

I would prefer to just have one shared task to create a cluster.

**Comment by TheoBrigitte** [comment]
> Can you give some context here? Why does `create-cluster` not work?
> 
> I would prefer to just have one shared task to create a cluster.

Yes I agree, my first idea was to use `gsctl` to create a cluster because I though the `create-cluster` task was already too specific. But I found out its not specific and works for me, so I'm trying to re-use this.

The issue here is that I am missing the `installation` file on disk. Would that be ok to move this to a parameter ? IIUC this file just hold one of the possible kubeconfig filename, e.g. `aws`.

**Comment by TheoBrigitte** [comment]
Found a workaround (wrote the installation name to disk)

Hitting a different error now

image

```
+ kubectl-gs template nodepool --provider aws --release v20.0.0 --organization giantswarm --cluster-name ey7f2 --description np1 --nodes-min 3 --nodes-max 10 --output /tmp/nodepool.yaml
Error: Invalid flag: --availability-zones must be configured with at least 1 AZ
```

**Comment by MarcelMue** [comment]
Maybe @fiunchinho can help here better? I would need to look up exactly how this currently works in other pipelines.

**Comment by fiunchinho** [comment]
I think having the provider as pipeline parameter makes sense, let's go for it.

**Comment by fiunchinho** [comment]
Most of these tasks have been used mostly on `azure` installations. I've looked into the issue and the problem is that `kubectl-gs` requires the `--availability-zones` parameter when using `aws`, but we haven't run into this problem before because we only used it on `azure`. Could you use `azure` for your tests?

**Comment by TheoBrigitte** [comment]
Closing outdated PR from an abandoned topic.

**Pull request closed without merging**
