### PR TITLE
heartbeat test setup

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/roadmap/issues/452

This PR does setup a new command with its associated pipeline and task which will serve as placeholder for the real heartbeat tests.

### CODE REVIEW

**Comment by MarcelMue** [comment]
You can test by deploying this to `gorilla/rfh2` - there is an app in the management cluster.

**Comment by TheoBrigitte** [comment]
> You can test by deploying this to `gorilla/rfh2` - there is an app in the management cluster.

Exactly what I found, but the hell do I deploy this ? via happa ?

**Comment by MarcelMue** [comment]
> > You can test by deploying this to `gorilla/rfh2` - there is an app in the management cluster.
> 
> Exactly what I found, but the hell do I deploy this ? via happa ?

You need to edit the `app CR` on the management cluster manually to point to your commit SHA currently :(

**Comment by TheoBrigitte** [comment]
Oh boy I just had an epiphany: https://github.com/giantswarm/opsctl/pull/1219

**Comment by TheoBrigitte** [comment]
This was tested and works :heavy_check_mark: 

- https://github.com/giantswarm/prometheus-meta-operator/pull/721
- 
image

image
[source](https://tekton.giantswarm.io/#/namespaces/test-workloads/pipelineruns/68fcbf04-16d2-11ec-959d-fa3ca8521a07?pipelineTask=hello-world&step=echo)

**Review by mig4 — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]
Nice! Test itself can follow in a later PR.

Thanks for putting in the effort and reusing our test setup :)

**Comment by TheoBrigitte** [comment]
> Nice! Test itself can follow in a later PR.
> 
> Thanks for putting in the effort and reusing our test setup :)

Thanks for actually providing this setup and some great documentation with it <3

**Pull request merged**
