### PR TITLE
Only upload results to S3 when tests fail

### PR DESCRIPTION
**Pull request by fiunchinho**
Towards https://github.com/giantswarm/giantswarm/issues/15856

These changes make the pipeline to *only* upload the test logs to S3 when tests fail. Before this, logs wouldn't be uploaded when tests fail.

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
makes a lot of sense

**Comment by stone-z** [comment]
My understanding was that `finally` is always run, not only in failure cases. Is that not the case?

**Review by stone-z — APPROVED** [review]
OK with me

**Comment by fiunchinho** [comment]
Apparently, `when` is only allowed in `finally` when using `tektoncd/pipeline` `v0.21.0`, and we use `v0.20.0`. I'll see how to upgrade.

**Pull request merged**
