### PR TITLE
Update aws.yaml

### PR DESCRIPTION
**Pull request by xh3b4sd**
Updating to the latest image and trying to inject the actual release version. I have to figure out how the deployment works again. 🙈

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
Looks reasonable

**Comment by MarcelMue** [comment]
Deployment works by editing the `test-infra` app in the `gorilla` CP. You can simply change the version to match the SHA of your commit here.

We are still tracking an improvement to the deployment process but the problem is not limited to test-infra but any TC app we have (and might want to redeploy automatically).

**Review by calvix — APPROVED** [review]
lgtmiwfy

**Comment by xh3b4sd** [comment]
This seems work as far as the configuration of `awscnfm` is concerned. There are missing RBAC rules now. Will sort this separately.

**Pull request merged**
