### PR TITLE
We need the cluster before we can allow IPs

### PR DESCRIPTION
**Pull request by fiunchinho**
Tested here https://tekton.giantswarm.io/#/namespaces/test-workloads/pipelineruns/1b150deb-34d2-11ed-8ee0-126ea5b5bffb

### CODE REVIEW

**Comment by calvix** [comment]
that sounds weird the  firewall rules should be applied once the cluster is created, it should not matter when you apply the annotation

you are sure its not something else?

**Comment by fiunchinho** [comment]
> that sounds weird, the firewall rules should be applied once the cluster is created, it should not matter when you apply the annotation
> 
> you are sure it's not something else?

What I mean is that I can't run `kubectl annotate` right after we run `kubectl apply` because at that point we have only applied the `Apps` but it takes a while for `app-operator` to pick that up and create the `GCPCluster` CR. This CR needs to exist before I can annotate it.

**Comment by calvix** [comment]
I thnik the main issue here is the `--overwrite `, as the annotation will exist  always, and if you don't add the values at start then it will be empty

so shuffling when its going to be applied is not really fixing anyhting

**Comment by fiunchinho** [comment]
If the `GCPCluster` CR does not exist I can't annotate it. I don't know what you mean. We need to wait for the `GCPCluster` to exist.

**Comment by calvix** [comment]
> If the `GCPCluster` CR does not exist I can't annotate it. I don't know what you mean. We need to wait for the `GCPCluster` to exist.

cluster is created here, including GCPCluster
https://github.com/giantswarm/test-infra/pull/201/files#diff-44929e69a454d11c6e1040e15e941ea5255fe7fe2a4584db7649eb4b101229a4R176

the `while` wait is just for the kubeconfig to exists not for the GCP CR

the order of it does not matter, you can apply annotation before kubeconfig exists or after, that's all I am saying, that the reordering serve  no purpose, but do whatever make you happy :)

**Comment by fiunchinho** [comment]
That's what I meant here https://github.com/giantswarm/test-infra/pull/201#issuecomment-1247799326

At that point that you link, we don't have the `Cluster` or `GCPCluster` CR yet. Only the `Apps`. We still need to wait for `app-operator` to reconcile the apps and create the CRs. Maybe I was unlucky but when I tested it that way, it failed due to the missing CRs. That's why I'm waiting for the kubeconfig to exists, because that grants me that the CRs are totally there by that point.

**Review by calvix — APPROVED** [review]
alright, gotcha

**Pull request merged**
